services:
  hytale-server:
    image: ghcr.io/slowline/hytale-docker
    build: .
    user: "1000:1000"
    container_name: hytale
    stdin_open: true
    tty: true
    ports:
      - "5520:5520/udp"
    volumes:
      - hytale-data:/hytale
      # Allows to persist server authorization with /auth persistence Encrypted
      # - /etc/machine-id:/etc/machine-id:ro
    env_file:
      - .env
    restart: unless-stopped

volumes:
  hytale-data: {}